version: "3"

services:
  nginx:
    build: "./service/nginx"
    volumes:
      - "./log/nginx:/var/log/nginx:rw"
      # 项目目录
      - "./hosts:/var/www/html:rw"
      - "./service/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./service/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./service/nginx/enable:/etc/nginx/enable:ro"
      - "./service/nginx/rewrite:/etc/nginx/rewrite:ro"
    ports:
      - "${PORT_NGINX_HTTP}:80"
      - "${PORT_NGINX_HTTP2}:443"
    expose:
      - "80"
      - "443"
    depends_on: 
      - php73
    networks:
      - web
    restart: always

  php73:
    build: "./service/php"
    volumes:
      # 项目目录
      - "./hosts:/var/www/html:rw"
      - "./service/php/php.ini:/usr/local/etc/php/php.ini:ro"
      - "./service/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro"
    restart: always
    networks:
      - web

  mysql:
    image: "mysql:8.0"
    volumes:
      - "./service/mysql/databases:/var/lib/mysql:rw"
      - "./service/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro"
      - "./log/mysql:/var/log/mysql"
    ports:
      - "${PORT_MYSQL}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    restart: always
    expose:
      - "3306"
    networks:
      - web
      
  redis507:
    image: "redis:5.0.7-alpine"
    volumes:
      - "./service/redis/data:/data:rw"
      - "./service/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro"
    ports:
      - "${REDIS_PORT}:6379"
    command: [redis-server,/usr/local/etc/redis/redis.conf]
    restart: always
    expose:
      - "6379"
    networks:
      - web

networks:
  web: