version: "3.1"

services:
  nginx:
    image: "nginx:alpine"
    volumes:
      - "${PUBLIC_LOG_PATH}/nginx:/var/log/nginx:rw"
      - "${PUBLIC_HOST_PATH}:/usr/share/nginx/html:ro"
      - "${PUBLIC_SERVICE_PATH}/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "${PUBLIC_SERVICE_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "${PUBLIC_SERVICE_PATH}/nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro"
    ports:
      - "${PORT_NGINX_HTTP}:80"
      - "${PORT_NGINX_HTTP2}:443"
    expose:
      - "80"
      - "443"

  php73:
    build: "${PUBLIC_SERVICE_PATH}/php"
    volumes:
      - "${PUBLIC_HOST_PATH}:/var/www/html:rw"
      - "${PUBLIC_SERVICE_PATH}/php/php.ini:/usr/local/etc/php/php.ini:ro"

  mysql:
    image: "mysql:5.7"
    volumes:
      - "${PUBLIC_SERVICE_PATH}/mysql/databases:/var/lib/mysql:rw"
      - "${PUBLIC_SERVICE_PATH}/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro"
    ports:
      - "${PORT_MYSQL}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    restart: always
    expose:
      - "3306"

  redis:
    image: "redis:5.0.7-alpine"
    volumes:
      - "${PUBLIC_SERVICE_PATH}/redis/data:/data:rw"
      - "${PUBLIC_SERVICE_PATH}/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro"
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]
    restart: always
    expose:
      - "6379"